module.exports = {
  plugins: {
    'postcss-import': {},
    tailwindcss: { config: './tailwind.public.config.js' },
    autoprefixer: {},
    ...(process.env.NODE_ENV === 'production' ? { 
      '@fullhuman/postcss-purgecss': {
        content: [
          './assets/css/public/**/*.css',
          './assets/css/blocks/**/*.css',
          './assets/css/shared/**/*.css',
          './assets/css/preline/**/*.css',
          './assets/css/wpify/**/*.css',
          './assets/js/public/**/*.{js,jsx}',
          './assets/js/public.js',
          './templates/public/**/*.php',
          './includes/Controllers/PublicController.php',
          './includes/Views/Blocks/Public/**/*.php',
          './includes/Blocks/**/*.php',
        ],
        defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || [],
        safelist: [
          // Public specific classes
          /^vc/,
          /^hs-/,
          /^google-map/,
          /^booking-/,
          /^leaflet/,
          /^gm-/,
          /^cs-/,
          /^summary-/,
          /^wpcbooking-/,
          /^hover:/,
          /^focus:/,
          /^disabled:/,
          /^dark:/,
          /^sm:/,
          /^md:/,
          /^lg:/,
          /^xl:/,
          /^2xl:/,
          // Animation classes
          /^animate-/,
          /^transition-/,
          /^duration-/,
          /^ease-/,
          // Dynamic classes that might be added by JavaScript
          /^active/,
          /^selected/,
          /^open/,
          /^closed/,
          /^expanded/,
          /^collapsed/,
          /^loading/,
          /^error/,
          /^success/,
          /^warning/,
          /^current/,
          /^available/,
          /^is-/,
          // Vanilla Calendar data attributes
          /data-vc/,
          /data-vc-date/,
          /data-vc-calendar/,
          /data-value/,
        ],
        // Keep important public styles
        whitelistPatterns: [
          /^vc/,
          /^hs-/,
          /^google-map/,
          /^booking-/,
          /^leaflet/,
          /^gm-/,
          /^cs-/,
          /^summary-/,
          /^wpcbooking-/,
          /^animate-/,
        ],
      },
      cssnano: {
        preset: ['default', {
          discardComments: {
            removeAll: true,
          },
          normalizeWhitespace: true,
          minifySelectors: true,
        }],
      },
    } : {}),
  },
}
